# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    # List iOS Devices & Platforms      
    - name: List iOS Devices & Platforms        
      run: |          
          xcrun simctl list      
          
    - name: check xcode version        
      run: |  
          xcodebuild -version
          swift --version
          xcrun simctl list runtimes
          xcrun simctl list devices 14.3
          UDID=$(
          xcrun simctl list |
          awk \
            -F ' *[][]' \
            -v 'device=iPhone 8 Plus (14.3)' \
            '$1 == device { print $2 }'
          )
