name:  Build and Test Flutter App
on: [push,pull_request]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
    strategy:
      matrix:
        device:
          - "iPhone 11 (14.3)"
  run: xcrun instruments -s
           |
          UDID=$(
            xcrun instruments -s |
            awk \
              -F ' *[][]' \
              -v 'device=${{ matrix.device }}' \
              '$1 == device { print $2 }'
          )
          xcrun simctl boot "${UDID:?No Simulator with this name found}"
