# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    # List iOS Devices & Platforms      
    - name: List iOS Devices & Platforms        
      run: |          
          xcrun simctl list      
      # Install iOS 11.4 Runtime      
    - name: check xcode version        
      run: |  
          xcodebuild -version
          swift --version
          open /Applications/Xcode.app/Contents/Developer/Applications/iOS\ Simulator.app/
