# Pre-Commit E2E Tests in iOS
name: Pre-Commit E2E Tests in iOS
# Controls when the action will run.
on:[push]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: macOS-latest
    steps:
      # List iOS Devices & Platforms      
      - name: List iOS Devices & Platforms        
        run: |          
          xcrun simctl list      
      # Install iOS 11.4 Runtime      
      - name: Install iOS 11.4 Runtime        
        run: |  
          gem install xcode-install
          xcversion simulators --install='iOS 11.4'
