name: Appium CI
# on push we will trigger our code
on: [push]


jobs:
  build:
    runs-on: macos-latest # the machine type
    steps:
    - uses: actions/checkout@v2 #checkout the code 
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install and Run Appium Server
      run: npm install -g appium
    - name: Run Appium Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        ndk: 21.0.6113669
        cmake: 3.10.2.4988404
        script: ./gradlew connectedCheck
        run: mvn verify
